default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: rails-todo_development

test:
  <<: *default
  database: rails-todo_development_test

production:
  <<: *default
